baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.de]
    weight = 2
    languageName = "Deutsch"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@skymatic/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

[markup.goldmark.renderer]
unsafe = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.5.14"
      filename = "Cryptomator-1.5.14-x64.exe"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.14/Cryptomator-1.5.14-x64.exe"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.14/Cryptomator-1.5.14-x64.exe.asc"
      checksum = "75cf02089fe13eb2f4da9d567f174cbd46f06ff031e45cb2d81183eb39997355"
    [params.releases.dmg]
      version = "1.5.14"
      filename = "Cryptomator-1.5.14.dmg"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.14/Cryptomator-1.5.14.dmg"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.14/Cryptomator-1.5.14.dmg.asc"
      checksum = "2c7edaa8beae6b0db06260910846b15a57f4950f68e5c4025513ead540809d4c"
    [params.releases.appimage]
      version = "1.5.14"
      filename = "cryptomator-1.5.14-x86_64.AppImage"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.14/cryptomator-1.5.14-x86_64.AppImage"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.14/cryptomator-1.5.14-x86_64.AppImage.asc"
      checksum = "e084d5afa25ae9539cc6b003df994d60307e97e7f45fa97221c978fc802c672e"
    [params.releases.android]
      version = "1.5.14"
      filename = "Cryptomator-1.5.14.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.5.14/Cryptomator-1.5.14.apk"
      checksum = "81de58e71d946d31458e06fb6f500c5f015fe3f2b3179ffac67d2542711d82e3"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
